<?php

/**
 * @file
 * Test specific changes for the photoswipe library test.
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_library_alter().
 */
function photoswipe_library_test_library_info_alter(&$libraries, $extension) {
  if ($extension === 'photoswipe') {
    foreach ($libraries['photoswipe.local']['js'] as $key => $library) {
      $libraries['photoswipe.local']['js']['/' . Settings::get('file_public_path') . $key] = $library;
      unset($libraries['photoswipe.local']['js'][$key]);
    }
  }
}
